### ISSUE TITLE
Please add support of `ibicaraiwebradio.com.br` as a music platform

### ISSUE THREAD

**Issue by forsaints** [AlexWayfer/song-lyrics#11]
I think it's appropriate for this extension. Thank you.

**Comment by AlexWayfer** [comment]
Sorry, I don't think it's possible, because the player has not enough information. Just a song name, even without artists.

I believe you can use [the Shazam extension](https://chromewebstore.google.com/detail/shazam-find-song-names-fr/mmioliijnhnoblpgimnlajmefafdfilb), and then, if you want to, use Song Lyrics extension on a Shazam page.

![image](https://github.com/AlexWayfer/song-lyrics/assets/6510020/1d569909-a94d-4df1-90e9-79d71fe5eea4)


I understand that this is +1 action, but I really see no possibility to parse the full current song name from this site.
